# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{taskbot}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Logan Koester"]
  s.date = %q{2011-03-21}
  s.default_executable = %q{taskbot}
  s.description = %q{Simple to-do lists implemented as an IRC robot}
  s.email = %q{logan@logankoester.com}
  s.executables = ["taskbot"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/taskbot",
    "lib/cinch/plugins/taskbot.rb",
    "lib/cinch/plugins/taskbot/task.rb",
    "lib/cinch/plugins/taskbot/tasks.rb",
    "lib/cinch/plugins/taskbot/user.rb",
    "lib/taskbot.rb"
  ]
  s.homepage = %q{http://github.com/logankoester/taskbot}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Simple to-do lists implemented as an IRC robot}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<cinch>, ["~> 1.1.2"])
      s.add_runtime_dependency(%q<mongo_mapper>, ["~> 0.8.6"])
      s.add_runtime_dependency(%q<bson_ext>, ["~> 1.2.4"])
      s.add_runtime_dependency(%q<daemons>, ["~> 1.1.0"])
      s.add_runtime_dependency(%q<optiflag>, ["~> 0.7"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
    else
      s.add_dependency(%q<cinch>, ["~> 1.1.2"])
      s.add_dependency(%q<mongo_mapper>, ["~> 0.8.6"])
      s.add_dependency(%q<bson_ext>, ["~> 1.2.4"])
      s.add_dependency(%q<daemons>, ["~> 1.1.0"])
      s.add_dependency(%q<optiflag>, ["~> 0.7"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    end
  else
    s.add_dependency(%q<cinch>, ["~> 1.1.2"])
    s.add_dependency(%q<mongo_mapper>, ["~> 0.8.6"])
    s.add_dependency(%q<bson_ext>, ["~> 1.2.4"])
    s.add_dependency(%q<daemons>, ["~> 1.1.0"])
    s.add_dependency(%q<optiflag>, ["~> 0.7"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
  end
end

